# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'wordle.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1046, 902)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout = QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.Combined = QWidget(self.centralwidget)
        self.Combined.setObjectName(u"Combined")
        self.Combined.setStyleSheet(u"background-color:#D8EFC2")
        self.verticalLayout = QVBoxLayout(self.Combined)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalSpacer_9 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer_9)

        self.theme = QPushButton(self.Combined)
        self.theme.setObjectName(u"theme")
        self.theme.setMinimumSize(QSize(83, 0))
        self.theme.setMaximumSize(QSize(83, 16777215))
        self.theme.setStyleSheet(u"border-top: 2px solid black; border-bottom: 2px solid black;")

        self.horizontalLayout.addWidget(self.theme)

        self.rules = QPushButton(self.Combined)
        self.rules.setObjectName(u"rules")
        self.rules.setMinimumSize(QSize(83, 0))
        self.rules.setMaximumSize(QSize(83, 16777215))
        self.rules.setStyleSheet(u"border-top: 2px solid black; border-bottom: 2px solid black;")

        self.horizontalLayout.addWidget(self.rules)

        self.horizontalLayout.setStretch(0, 10)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 1)

        self.verticalLayout.addLayout(self.horizontalLayout)

        self.Windows = QWidget(self.Combined)
        self.Windows.setObjectName(u"Windows")
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Windows.sizePolicy().hasHeightForWidth())
        self.Windows.setSizePolicy(sizePolicy)
        self.Windows.setFocusPolicy(Qt.NoFocus)
        self.Windows.setLayoutDirection(Qt.LeftToRight)
        self.Windows.setStyleSheet(u"border-top: 2px solid black;")
        self.gridLayout_2 = QGridLayout(self.Windows)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.r4c5 = QLabel(self.Windows)
        self.r4c5.setObjectName(u"r4c5")
        self.r4c5.setMinimumSize(QSize(57, 67))
        self.r4c5.setMaximumSize(QSize(57, 67))
        font = QFont()
        font.setFamily(u"DejaVu Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.r4c5.setFont(font)
        self.r4c5.setStyleSheet(u"border: 1px solid black; background-color: white;")
        self.r4c5.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.r4c5, 6, 5, 1, 1)

        self.r2c2 = QLabel(self.Windows)
        self.r2c2.setObjectName(u"r2c2")
        self.r2c2.setMinimumSize(QSize(57, 67))
        self.r2c2.setMaximumSize(QSize(57, 67))
        self.r2c2.setFont(font)
        self.r2c2.setStyleSheet(u"border: 1px solid black; background-color: white;")
        self.r2c2.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.r2c2, 4, 2, 1, 1)

        self.horizontalSpacer_2 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.gridLayout_2.addItem(self.horizontalSpacer_2, 5, 6, 1, 1)

        self.r5c1 = QLabel(self.Windows)
        self.r5c1.setObjectName(u"r5c1")
        self.r5c1.setMinimumSize(QSize(57, 67))
        self.r5c1.setMaximumSize(QSize(57, 67))
        self.r5c1.setFont(font)
        self.r5c1.setStyleSheet(u"border: 1px solid black; background-color: white;")
        self.r5c1.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.r5c1, 7, 1, 1, 1)

        self.r4c2 = QLabel(self.Windows)
        self.r4c2.setObjectName(u"r4c2")
        self.r4c2.setMinimumSize(QSize(57, 67))
        self.r4c2.setMaximumSize(QSize(57, 67))
        self.r4c2.setFont(font)
        self.r4c2.setStyleSheet(u"border: 1px solid black; background-color: white;")
        self.r4c2.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.r4c2, 6, 2, 1, 1)

        self.r3c5 = QLabel(self.Windows)
        self.r3c5.setObjectName(u"r3c5")
        self.r3c5.setMinimumSize(QSize(57, 67))
        self.r3c5.setMaximumSize(QSize(57, 67))
        self.r3c5.setFont(font)
        self.r3c5.setStyleSheet(u"border: 1px solid black; background-color: white;")
        self.r3c5.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.r3c5, 5, 5, 1, 1)

        self.r5c5 = QLabel(self.Windows)
        self.r5c5.setObjectName(u"r5c5")
        self.r5c5.setMinimumSize(QSize(57, 67))
        self.r5c5.setMaximumSize(QSize(57, 67))
        self.r5c5.setFont(font)
        self.r5c5.setStyleSheet(u"border: 1px solid black; background-color: white;")
        self.r5c5.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.r5c5, 7, 5, 1, 1)

        self.verticalSpacer_2 = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.gridLayout_2.addItem(self.verticalSpacer_2, 9, 3, 1, 1)

        self.r3c1 = QLabel(self.Windows)
        self.r3c1.setObjectName(u"r3c1")
        self.r3c1.setMinimumSize(QSize(57, 67))
        self.r3c1.setMaximumSize(QSize(57, 67))
        self.r3c1.setFont(font)
        self.r3c1.setStyleSheet(u"border: 1px solid black; background-color: white;")
        self.r3c1.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.r3c1, 5, 1, 1, 1)

        self.r4c4 = QLabel(self.Windows)
        self.r4c4.setObjectName(u"r4c4")
        self.r4c4.setMinimumSize(QSize(57, 67))
        self.r4c4.setMaximumSize(QSize(57, 67))
        self.r4c4.setFont(font)
        self.r4c4.setStyleSheet(u"border: 1px solid black; background-color: white;")
        self.r4c4.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.r4c4, 6, 4, 1, 1)

        self.verticalSpacer = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.gridLayout_2.addItem(self.verticalSpacer, 2, 3, 1, 1)

        self.r2c5 = QLabel(self.Windows)
        self.r2c5.setObjectName(u"r2c5")
        self.r2c5.setMinimumSize(QSize(57, 67))
        self.r2c5.setMaximumSize(QSize(57, 67))
        self.r2c5.setFont(font)
        self.r2c5.setStyleSheet(u"border: 1px solid black; background-color: white;")
        self.r2c5.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.r2c5, 4, 5, 1, 1)

        self.r1c2 = QLabel(self.Windows)
        self.r1c2.setObjectName(u"r1c2")
        self.r1c2.setMinimumSize(QSize(57, 67))
        self.r1c2.setMaximumSize(QSize(57, 67))
        self.r1c2.setFont(font)
        self.r1c2.setStyleSheet(u"border: 1px solid black; background-color: white;")
        self.r1c2.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.r1c2, 3, 2, 1, 1)

        self.r3c3 = QLabel(self.Windows)
        self.r3c3.setObjectName(u"r3c3")
        self.r3c3.setMinimumSize(QSize(57, 67))
        self.r3c3.setMaximumSize(QSize(57, 67))
        self.r3c3.setFont(font)
        self.r3c3.setStyleSheet(u"border: 1px solid black; background-color: white;")
        self.r3c3.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.r3c3, 5, 3, 1, 1)

        self.r6c1 = QLabel(self.Windows)
        self.r6c1.setObjectName(u"r6c1")
        self.r6c1.setMinimumSize(QSize(57, 67))
        self.r6c1.setMaximumSize(QSize(57, 67))
        self.r6c1.setFont(font)
        self.r6c1.setStyleSheet(u"border: 1px solid black; background-color: white;")
        self.r6c1.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.r6c1, 8, 1, 1, 1)

        self.r3c4 = QLabel(self.Windows)
        self.r3c4.setObjectName(u"r3c4")
        self.r3c4.setMinimumSize(QSize(57, 67))
        self.r3c4.setMaximumSize(QSize(57, 67))
        self.r3c4.setFont(font)
        self.r3c4.setStyleSheet(u"border: 1px solid black; background-color: white;")
        self.r3c4.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.r3c4, 5, 4, 1, 1)

        self.r1c4 = QLabel(self.Windows)
        self.r1c4.setObjectName(u"r1c4")
        self.r1c4.setMinimumSize(QSize(57, 67))
        self.r1c4.setMaximumSize(QSize(57, 67))
        self.r1c4.setFont(font)
        self.r1c4.setStyleSheet(u"border: 1px solid black; background-color: white;")
        self.r1c4.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.r1c4, 3, 4, 1, 1)

        self.horizontalSpacer = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.gridLayout_2.addItem(self.horizontalSpacer, 5, 0, 1, 1)

        self.r2c3 = QLabel(self.Windows)
        self.r2c3.setObjectName(u"r2c3")
        self.r2c3.setMinimumSize(QSize(57, 67))
        self.r2c3.setMaximumSize(QSize(57, 67))
        self.r2c3.setFont(font)
        self.r2c3.setStyleSheet(u"border: 1px solid black; background-color: white;")
        self.r2c3.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.r2c3, 4, 3, 1, 1)

        self.r4c1 = QLabel(self.Windows)
        self.r4c1.setObjectName(u"r4c1")
        self.r4c1.setMinimumSize(QSize(57, 67))
        self.r4c1.setMaximumSize(QSize(57, 67))
        self.r4c1.setFont(font)
        self.r4c1.setStyleSheet(u"border: 1px solid black; background-color: white;")
        self.r4c1.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.r4c1, 6, 1, 1, 1)

        self.r6c4 = QLabel(self.Windows)
        self.r6c4.setObjectName(u"r6c4")
        self.r6c4.setMinimumSize(QSize(57, 67))
        self.r6c4.setMaximumSize(QSize(57, 67))
        self.r6c4.setFont(font)
        self.r6c4.setStyleSheet(u"border: 1px solid black; background-color: white;")
        self.r6c4.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.r6c4, 8, 4, 1, 1)

        self.r2c4 = QLabel(self.Windows)
        self.r2c4.setObjectName(u"r2c4")
        self.r2c4.setMinimumSize(QSize(57, 67))
        self.r2c4.setMaximumSize(QSize(57, 67))
        self.r2c4.setFont(font)
        self.r2c4.setStyleSheet(u"border: 1px solid black; background-color: white;")
        self.r2c4.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.r2c4, 4, 4, 1, 1)

        self.r6c3 = QLabel(self.Windows)
        self.r6c3.setObjectName(u"r6c3")
        self.r6c3.setMinimumSize(QSize(57, 67))
        self.r6c3.setMaximumSize(QSize(57, 67))
        self.r6c3.setFont(font)
        self.r6c3.setStyleSheet(u"border: 1px solid black; background-color: white;")
        self.r6c3.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.r6c3, 8, 3, 1, 1)

        self.r6c2 = QLabel(self.Windows)
        self.r6c2.setObjectName(u"r6c2")
        self.r6c2.setMinimumSize(QSize(57, 67))
        self.r6c2.setMaximumSize(QSize(57, 67))
        self.r6c2.setFont(font)
        self.r6c2.setStyleSheet(u"border: 1px solid black; background-color: white;")
        self.r6c2.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.r6c2, 8, 2, 1, 1)

        self.r5c3 = QLabel(self.Windows)
        self.r5c3.setObjectName(u"r5c3")
        self.r5c3.setMinimumSize(QSize(57, 67))
        self.r5c3.setMaximumSize(QSize(57, 67))
        self.r5c3.setFont(font)
        self.r5c3.setStyleSheet(u"border: 1px solid black; background-color: white;")
        self.r5c3.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.r5c3, 7, 3, 1, 1)

        self.r5c2 = QLabel(self.Windows)
        self.r5c2.setObjectName(u"r5c2")
        self.r5c2.setMinimumSize(QSize(57, 67))
        self.r5c2.setMaximumSize(QSize(57, 67))
        self.r5c2.setFont(font)
        self.r5c2.setStyleSheet(u"border: 1px solid black; background-color: white;")
        self.r5c2.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.r5c2, 7, 2, 1, 1)

        self.r3c2 = QLabel(self.Windows)
        self.r3c2.setObjectName(u"r3c2")
        self.r3c2.setMinimumSize(QSize(57, 67))
        self.r3c2.setMaximumSize(QSize(57, 67))
        self.r3c2.setFont(font)
        self.r3c2.setStyleSheet(u"border: 1px solid black; background-color: white;")
        self.r3c2.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.r3c2, 5, 2, 1, 1)

        self.r2c1 = QLabel(self.Windows)
        self.r2c1.setObjectName(u"r2c1")
        self.r2c1.setMinimumSize(QSize(57, 67))
        self.r2c1.setMaximumSize(QSize(57, 67))
        self.r2c1.setFont(font)
        self.r2c1.setStyleSheet(u"border: 1px solid black; background-color: white;")
        self.r2c1.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.r2c1, 4, 1, 1, 1)

        self.r1c3 = QLabel(self.Windows)
        self.r1c3.setObjectName(u"r1c3")
        self.r1c3.setMinimumSize(QSize(57, 67))
        self.r1c3.setMaximumSize(QSize(57, 67))
        self.r1c3.setFont(font)
        self.r1c3.setStyleSheet(u"border: 1px solid black; background-color: white;")
        self.r1c3.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.r1c3, 3, 3, 1, 1)

        self.r1c5 = QLabel(self.Windows)
        self.r1c5.setObjectName(u"r1c5")
        self.r1c5.setMinimumSize(QSize(57, 67))
        self.r1c5.setMaximumSize(QSize(57, 67))
        self.r1c5.setFont(font)
        self.r1c5.setStyleSheet(u"border: 1px solid black; background-color: white;")
        self.r1c5.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.r1c5, 3, 5, 1, 1)

        self.r1c1 = QLabel(self.Windows)
        self.r1c1.setObjectName(u"r1c1")
        self.r1c1.setMinimumSize(QSize(57, 67))
        self.r1c1.setMaximumSize(QSize(57, 67))
        self.r1c1.setFont(font)
        self.r1c1.setStyleSheet(u"border: 1px solid black; background-color: white;")
        self.r1c1.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.r1c1, 3, 1, 1, 1)

        self.r6c5 = QLabel(self.Windows)
        self.r6c5.setObjectName(u"r6c5")
        self.r6c5.setMinimumSize(QSize(57, 67))
        self.r6c5.setMaximumSize(QSize(57, 67))
        self.r6c5.setFont(font)
        self.r6c5.setStyleSheet(u"border: 1px solid black; background-color: white;")
        self.r6c5.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.r6c5, 8, 5, 1, 1)

        self.r5c4 = QLabel(self.Windows)
        self.r5c4.setObjectName(u"r5c4")
        self.r5c4.setMinimumSize(QSize(57, 67))
        self.r5c4.setMaximumSize(QSize(57, 67))
        self.r5c4.setFont(font)
        self.r5c4.setStyleSheet(u"border: 1px solid black; background-color: white;")
        self.r5c4.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.r5c4, 7, 4, 1, 1)

        self.r4c3 = QLabel(self.Windows)
        self.r4c3.setObjectName(u"r4c3")
        self.r4c3.setMinimumSize(QSize(57, 67))
        self.r4c3.setMaximumSize(QSize(57, 67))
        self.r4c3.setFont(font)
        self.r4c3.setStyleSheet(u"border: 1px solid black; background-color: white;")
        self.r4c3.setAlignment(Qt.AlignCenter)

        self.gridLayout_2.addWidget(self.r4c3, 6, 3, 1, 1)

        self.gridLayout_2.setRowStretch(0, 1)
        self.gridLayout_2.setRowStretch(1, 2)
        self.gridLayout_2.setRowStretch(2, 2)
        self.gridLayout_2.setRowStretch(3, 2)
        self.gridLayout_2.setRowStretch(4, 2)
        self.gridLayout_2.setRowStretch(5, 2)
        self.gridLayout_2.setRowStretch(6, 2)
        self.gridLayout_2.setRowStretch(7, 1)
        self.gridLayout_2.setColumnStretch(0, 6)
        self.gridLayout_2.setColumnStretch(1, 1)
        self.gridLayout_2.setColumnStretch(2, 1)
        self.gridLayout_2.setColumnStretch(3, 1)
        self.gridLayout_2.setColumnStretch(4, 1)
        self.gridLayout_2.setColumnStretch(5, 1)
        self.gridLayout_2.setColumnStretch(6, 6)

        self.verticalLayout.addWidget(self.Windows)

        self.Keyboard = QWidget(self.Combined)
        self.Keyboard.setObjectName(u"Keyboard")
        sizePolicy.setHeightForWidth(self.Keyboard.sizePolicy().hasHeightForWidth())
        self.Keyboard.setSizePolicy(sizePolicy)
        self.verticalLayout_2 = QVBoxLayout(self.Keyboard)
        self.verticalLayout_2.setSpacing(1)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalSpacer_3 = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.verticalLayout_2.addItem(self.verticalSpacer_3)

        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setSpacing(1)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalSpacer_3 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout_2.addItem(self.horizontalSpacer_3)

        self.qq = QPushButton(self.Keyboard)
        self.all_buttons = QButtonGroup(MainWindow)
        self.all_buttons.setObjectName(u"all_buttons")
        self.all_buttons.addButton(self.qq)
        self.qq.setObjectName(u"qq")
        sizePolicy1 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Minimum)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.qq.sizePolicy().hasHeightForWidth())
        self.qq.setSizePolicy(sizePolicy1)
        self.qq.setMinimumSize(QSize(70, 62))
        self.qq.setMaximumSize(QSize(70, 62))
        font1 = QFont()
        font1.setFamily(u"DejaVu Sans")
        font1.setBold(False)
        font1.setWeight(50)
        self.qq.setFont(font1)
        self.qq.setStyleSheet(u"border: 1px solid black; background-color:white;")

        self.horizontalLayout_2.addWidget(self.qq)

        self.ww = QPushButton(self.Keyboard)
        self.all_buttons.addButton(self.ww)
        self.ww.setObjectName(u"ww")
        sizePolicy1.setHeightForWidth(self.ww.sizePolicy().hasHeightForWidth())
        self.ww.setSizePolicy(sizePolicy1)
        self.ww.setMinimumSize(QSize(70, 62))
        self.ww.setMaximumSize(QSize(70, 62))
        self.ww.setFont(font1)
        self.ww.setStyleSheet(u"border: 1px solid black; background-color:white;")

        self.horizontalLayout_2.addWidget(self.ww)

        self.ee = QPushButton(self.Keyboard)
        self.all_buttons.addButton(self.ee)
        self.ee.setObjectName(u"ee")
        sizePolicy1.setHeightForWidth(self.ee.sizePolicy().hasHeightForWidth())
        self.ee.setSizePolicy(sizePolicy1)
        self.ee.setMinimumSize(QSize(70, 62))
        self.ee.setMaximumSize(QSize(70, 62))
        self.ee.setFont(font1)
        self.ee.setStyleSheet(u"border: 1px solid black; background-color:white;")

        self.horizontalLayout_2.addWidget(self.ee)

        self.rr = QPushButton(self.Keyboard)
        self.all_buttons.addButton(self.rr)
        self.rr.setObjectName(u"rr")
        sizePolicy1.setHeightForWidth(self.rr.sizePolicy().hasHeightForWidth())
        self.rr.setSizePolicy(sizePolicy1)
        self.rr.setMinimumSize(QSize(70, 62))
        self.rr.setMaximumSize(QSize(70, 62))
        self.rr.setFont(font1)
        self.rr.setStyleSheet(u"border: 1px solid black; background-color:white;")

        self.horizontalLayout_2.addWidget(self.rr)

        self.tt = QPushButton(self.Keyboard)
        self.all_buttons.addButton(self.tt)
        self.tt.setObjectName(u"tt")
        sizePolicy1.setHeightForWidth(self.tt.sizePolicy().hasHeightForWidth())
        self.tt.setSizePolicy(sizePolicy1)
        self.tt.setMinimumSize(QSize(70, 62))
        self.tt.setMaximumSize(QSize(70, 62))
        self.tt.setFont(font1)
        self.tt.setStyleSheet(u"border: 1px solid black; background-color:white;")

        self.horizontalLayout_2.addWidget(self.tt)

        self.yy = QPushButton(self.Keyboard)
        self.all_buttons.addButton(self.yy)
        self.yy.setObjectName(u"yy")
        sizePolicy1.setHeightForWidth(self.yy.sizePolicy().hasHeightForWidth())
        self.yy.setSizePolicy(sizePolicy1)
        self.yy.setMinimumSize(QSize(70, 62))
        self.yy.setMaximumSize(QSize(70, 62))
        self.yy.setFont(font1)
        self.yy.setStyleSheet(u"border: 1px solid black; background-color:white;")

        self.horizontalLayout_2.addWidget(self.yy)

        self.uu = QPushButton(self.Keyboard)
        self.all_buttons.addButton(self.uu)
        self.uu.setObjectName(u"uu")
        sizePolicy1.setHeightForWidth(self.uu.sizePolicy().hasHeightForWidth())
        self.uu.setSizePolicy(sizePolicy1)
        self.uu.setMinimumSize(QSize(70, 62))
        self.uu.setMaximumSize(QSize(70, 62))
        self.uu.setFont(font1)
        self.uu.setStyleSheet(u"border: 1px solid black; background-color:white;")

        self.horizontalLayout_2.addWidget(self.uu)

        self.ii = QPushButton(self.Keyboard)
        self.all_buttons.addButton(self.ii)
        self.ii.setObjectName(u"ii")
        sizePolicy1.setHeightForWidth(self.ii.sizePolicy().hasHeightForWidth())
        self.ii.setSizePolicy(sizePolicy1)
        self.ii.setMinimumSize(QSize(70, 62))
        self.ii.setMaximumSize(QSize(70, 62))
        self.ii.setFont(font1)
        self.ii.setStyleSheet(u"border: 1px solid black; background-color:white;")

        self.horizontalLayout_2.addWidget(self.ii)

        self.oo = QPushButton(self.Keyboard)
        self.all_buttons.addButton(self.oo)
        self.oo.setObjectName(u"oo")
        sizePolicy1.setHeightForWidth(self.oo.sizePolicy().hasHeightForWidth())
        self.oo.setSizePolicy(sizePolicy1)
        self.oo.setMinimumSize(QSize(70, 62))
        self.oo.setMaximumSize(QSize(70, 62))
        self.oo.setFont(font1)
        self.oo.setStyleSheet(u"border: 1px solid black; background-color:white;")

        self.horizontalLayout_2.addWidget(self.oo)

        self.pp = QPushButton(self.Keyboard)
        self.all_buttons.addButton(self.pp)
        self.pp.setObjectName(u"pp")
        sizePolicy1.setHeightForWidth(self.pp.sizePolicy().hasHeightForWidth())
        self.pp.setSizePolicy(sizePolicy1)
        self.pp.setMinimumSize(QSize(70, 62))
        self.pp.setMaximumSize(QSize(70, 62))
        self.pp.setFont(font1)
        self.pp.setStyleSheet(u"border: 1px solid black; background-color:white;")

        self.horizontalLayout_2.addWidget(self.pp)

        self.horizontalSpacer_7 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout_2.addItem(self.horizontalSpacer_7)

        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 1)
        self.horizontalLayout_2.setStretch(2, 1)
        self.horizontalLayout_2.setStretch(3, 1)
        self.horizontalLayout_2.setStretch(4, 1)
        self.horizontalLayout_2.setStretch(5, 1)
        self.horizontalLayout_2.setStretch(6, 1)
        self.horizontalLayout_2.setStretch(7, 1)
        self.horizontalLayout_2.setStretch(8, 1)
        self.horizontalLayout_2.setStretch(9, 1)
        self.horizontalLayout_2.setStretch(10, 1)
        self.horizontalLayout_2.setStretch(11, 2)

        self.verticalLayout_2.addLayout(self.horizontalLayout_2)

        self.horizontalLayout_3 = QHBoxLayout()
        self.horizontalLayout_3.setSpacing(1)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalSpacer_5 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout_3.addItem(self.horizontalSpacer_5)

        self.aa = QPushButton(self.Keyboard)
        self.all_buttons.addButton(self.aa)
        self.aa.setObjectName(u"aa")
        sizePolicy1.setHeightForWidth(self.aa.sizePolicy().hasHeightForWidth())
        self.aa.setSizePolicy(sizePolicy1)
        self.aa.setMinimumSize(QSize(70, 62))
        self.aa.setMaximumSize(QSize(70, 62))
        self.aa.setFont(font1)
        self.aa.setStyleSheet(u"border: 1px solid black; background-color:white;")

        self.horizontalLayout_3.addWidget(self.aa)

        self.ss = QPushButton(self.Keyboard)
        self.all_buttons.addButton(self.ss)
        self.ss.setObjectName(u"ss")
        sizePolicy1.setHeightForWidth(self.ss.sizePolicy().hasHeightForWidth())
        self.ss.setSizePolicy(sizePolicy1)
        self.ss.setMinimumSize(QSize(70, 62))
        self.ss.setMaximumSize(QSize(70, 62))
        self.ss.setFont(font1)
        self.ss.setStyleSheet(u"border: 1px solid black; background-color:white;")

        self.horizontalLayout_3.addWidget(self.ss)

        self.dd = QPushButton(self.Keyboard)
        self.all_buttons.addButton(self.dd)
        self.dd.setObjectName(u"dd")
        sizePolicy1.setHeightForWidth(self.dd.sizePolicy().hasHeightForWidth())
        self.dd.setSizePolicy(sizePolicy1)
        self.dd.setMinimumSize(QSize(70, 62))
        self.dd.setMaximumSize(QSize(70, 62))
        self.dd.setFont(font1)
        self.dd.setStyleSheet(u"border: 1px solid black; background-color:white;")

        self.horizontalLayout_3.addWidget(self.dd)

        self.ff = QPushButton(self.Keyboard)
        self.all_buttons.addButton(self.ff)
        self.ff.setObjectName(u"ff")
        sizePolicy1.setHeightForWidth(self.ff.sizePolicy().hasHeightForWidth())
        self.ff.setSizePolicy(sizePolicy1)
        self.ff.setMinimumSize(QSize(70, 62))
        self.ff.setMaximumSize(QSize(70, 62))
        self.ff.setFont(font1)
        self.ff.setStyleSheet(u"border: 1px solid black; background-color:white;")

        self.horizontalLayout_3.addWidget(self.ff)

        self.gg = QPushButton(self.Keyboard)
        self.all_buttons.addButton(self.gg)
        self.gg.setObjectName(u"gg")
        sizePolicy1.setHeightForWidth(self.gg.sizePolicy().hasHeightForWidth())
        self.gg.setSizePolicy(sizePolicy1)
        self.gg.setMinimumSize(QSize(70, 62))
        self.gg.setMaximumSize(QSize(70, 62))
        self.gg.setFont(font1)
        self.gg.setStyleSheet(u"border: 1px solid black; background-color:white;")

        self.horizontalLayout_3.addWidget(self.gg)

        self.hh = QPushButton(self.Keyboard)
        self.all_buttons.addButton(self.hh)
        self.hh.setObjectName(u"hh")
        sizePolicy1.setHeightForWidth(self.hh.sizePolicy().hasHeightForWidth())
        self.hh.setSizePolicy(sizePolicy1)
        self.hh.setMinimumSize(QSize(70, 62))
        self.hh.setMaximumSize(QSize(70, 62))
        self.hh.setFont(font1)
        self.hh.setStyleSheet(u"border: 1px solid black; background-color:white;")

        self.horizontalLayout_3.addWidget(self.hh)

        self.jj = QPushButton(self.Keyboard)
        self.all_buttons.addButton(self.jj)
        self.jj.setObjectName(u"jj")
        sizePolicy1.setHeightForWidth(self.jj.sizePolicy().hasHeightForWidth())
        self.jj.setSizePolicy(sizePolicy1)
        self.jj.setMinimumSize(QSize(70, 62))
        self.jj.setMaximumSize(QSize(70, 62))
        self.jj.setFont(font1)
        self.jj.setStyleSheet(u"border: 1px solid black; background-color:white;")

        self.horizontalLayout_3.addWidget(self.jj)

        self.kk = QPushButton(self.Keyboard)
        self.all_buttons.addButton(self.kk)
        self.kk.setObjectName(u"kk")
        sizePolicy1.setHeightForWidth(self.kk.sizePolicy().hasHeightForWidth())
        self.kk.setSizePolicy(sizePolicy1)
        self.kk.setMinimumSize(QSize(70, 62))
        self.kk.setMaximumSize(QSize(70, 62))
        self.kk.setFont(font1)
        self.kk.setStyleSheet(u"border: 1px solid black; background-color:white;")

        self.horizontalLayout_3.addWidget(self.kk)

        self.ll = QPushButton(self.Keyboard)
        self.all_buttons.addButton(self.ll)
        self.ll.setObjectName(u"ll")
        sizePolicy1.setHeightForWidth(self.ll.sizePolicy().hasHeightForWidth())
        self.ll.setSizePolicy(sizePolicy1)
        self.ll.setMinimumSize(QSize(70, 62))
        self.ll.setMaximumSize(QSize(70, 62))
        self.ll.setFont(font1)
        self.ll.setStyleSheet(u"border: 1px solid black; background-color:white;")

        self.horizontalLayout_3.addWidget(self.ll)

        self.horizontalSpacer_4 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout_3.addItem(self.horizontalSpacer_4)

        self.horizontalLayout_3.setStretch(0, 5)
        self.horizontalLayout_3.setStretch(1, 2)
        self.horizontalLayout_3.setStretch(2, 2)
        self.horizontalLayout_3.setStretch(3, 2)
        self.horizontalLayout_3.setStretch(4, 2)
        self.horizontalLayout_3.setStretch(5, 2)
        self.horizontalLayout_3.setStretch(6, 2)
        self.horizontalLayout_3.setStretch(7, 2)
        self.horizontalLayout_3.setStretch(8, 2)
        self.horizontalLayout_3.setStretch(9, 2)
        self.horizontalLayout_3.setStretch(10, 5)

        self.verticalLayout_2.addLayout(self.horizontalLayout_3)

        self.horizontalLayout_4 = QHBoxLayout()
        self.horizontalLayout_4.setSpacing(1)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.horizontalSpacer_6 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout_4.addItem(self.horizontalSpacer_6)

        self.enter = QPushButton(self.Keyboard)
        self.all_buttons.addButton(self.enter)
        self.enter.setObjectName(u"enter")
        sizePolicy1.setHeightForWidth(self.enter.sizePolicy().hasHeightForWidth())
        self.enter.setSizePolicy(sizePolicy1)
        self.enter.setMinimumSize(QSize(105, 62))
        self.enter.setMaximumSize(QSize(105, 62))
        self.enter.setFont(font1)
        self.enter.setStyleSheet(u"border: 1px solid black; background-color:white;")

        self.horizontalLayout_4.addWidget(self.enter)

        self.zz = QPushButton(self.Keyboard)
        self.all_buttons.addButton(self.zz)
        self.zz.setObjectName(u"zz")
        sizePolicy1.setHeightForWidth(self.zz.sizePolicy().hasHeightForWidth())
        self.zz.setSizePolicy(sizePolicy1)
        self.zz.setMinimumSize(QSize(70, 62))
        self.zz.setMaximumSize(QSize(70, 62))
        self.zz.setFont(font1)
        self.zz.setStyleSheet(u"border: 1px solid black; background-color:white;")

        self.horizontalLayout_4.addWidget(self.zz)

        self.xx = QPushButton(self.Keyboard)
        self.all_buttons.addButton(self.xx)
        self.xx.setObjectName(u"xx")
        sizePolicy1.setHeightForWidth(self.xx.sizePolicy().hasHeightForWidth())
        self.xx.setSizePolicy(sizePolicy1)
        self.xx.setMinimumSize(QSize(70, 62))
        self.xx.setMaximumSize(QSize(70, 62))
        self.xx.setFont(font1)
        self.xx.setStyleSheet(u"border: 1px solid black; background-color:white;")

        self.horizontalLayout_4.addWidget(self.xx)

        self.cc = QPushButton(self.Keyboard)
        self.all_buttons.addButton(self.cc)
        self.cc.setObjectName(u"cc")
        sizePolicy1.setHeightForWidth(self.cc.sizePolicy().hasHeightForWidth())
        self.cc.setSizePolicy(sizePolicy1)
        self.cc.setMinimumSize(QSize(70, 62))
        self.cc.setMaximumSize(QSize(70, 62))
        self.cc.setFont(font1)
        self.cc.setStyleSheet(u"border: 1px solid black; background-color:white;")

        self.horizontalLayout_4.addWidget(self.cc)

        self.vv = QPushButton(self.Keyboard)
        self.all_buttons.addButton(self.vv)
        self.vv.setObjectName(u"vv")
        sizePolicy1.setHeightForWidth(self.vv.sizePolicy().hasHeightForWidth())
        self.vv.setSizePolicy(sizePolicy1)
        self.vv.setMinimumSize(QSize(70, 62))
        self.vv.setMaximumSize(QSize(70, 62))
        self.vv.setFont(font1)
        self.vv.setStyleSheet(u"border: 1px solid black; background-color:white;")

        self.horizontalLayout_4.addWidget(self.vv)

        self.bb = QPushButton(self.Keyboard)
        self.all_buttons.addButton(self.bb)
        self.bb.setObjectName(u"bb")
        sizePolicy1.setHeightForWidth(self.bb.sizePolicy().hasHeightForWidth())
        self.bb.setSizePolicy(sizePolicy1)
        self.bb.setMinimumSize(QSize(70, 62))
        self.bb.setMaximumSize(QSize(70, 62))
        self.bb.setFont(font1)
        self.bb.setStyleSheet(u"border: 1px solid black; background-color:white;")

        self.horizontalLayout_4.addWidget(self.bb)

        self.nn = QPushButton(self.Keyboard)
        self.all_buttons.addButton(self.nn)
        self.nn.setObjectName(u"nn")
        sizePolicy1.setHeightForWidth(self.nn.sizePolicy().hasHeightForWidth())
        self.nn.setSizePolicy(sizePolicy1)
        self.nn.setMinimumSize(QSize(70, 62))
        self.nn.setMaximumSize(QSize(70, 62))
        self.nn.setFont(font1)
        self.nn.setStyleSheet(u"border: 1px solid black; background-color:white;")

        self.horizontalLayout_4.addWidget(self.nn)

        self.mm = QPushButton(self.Keyboard)
        self.all_buttons.addButton(self.mm)
        self.mm.setObjectName(u"mm")
        sizePolicy1.setHeightForWidth(self.mm.sizePolicy().hasHeightForWidth())
        self.mm.setSizePolicy(sizePolicy1)
        self.mm.setMinimumSize(QSize(70, 62))
        self.mm.setMaximumSize(QSize(70, 62))
        self.mm.setFont(font1)
        self.mm.setStyleSheet(u"border: 1px solid black; background-color:white;")

        self.horizontalLayout_4.addWidget(self.mm)

        self.Backspace = QPushButton(self.Keyboard)
        self.all_buttons.addButton(self.Backspace)
        self.Backspace.setObjectName(u"Backspace")
        sizePolicy1.setHeightForWidth(self.Backspace.sizePolicy().hasHeightForWidth())
        self.Backspace.setSizePolicy(sizePolicy1)
        self.Backspace.setMinimumSize(QSize(105, 62))
        self.Backspace.setMaximumSize(QSize(105, 62))
        self.Backspace.setFont(font1)
        self.Backspace.setStyleSheet(u"border: 1px solid black; background-color:white;")

        self.horizontalLayout_4.addWidget(self.Backspace)

        self.horizontalSpacer_8 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout_4.addItem(self.horizontalSpacer_8)

        self.horizontalLayout_4.setStretch(0, 4)
        self.horizontalLayout_4.setStretch(1, 3)
        self.horizontalLayout_4.setStretch(2, 2)
        self.horizontalLayout_4.setStretch(3, 2)
        self.horizontalLayout_4.setStretch(4, 2)
        self.horizontalLayout_4.setStretch(5, 2)
        self.horizontalLayout_4.setStretch(6, 2)
        self.horizontalLayout_4.setStretch(7, 2)
        self.horizontalLayout_4.setStretch(8, 2)
        self.horizontalLayout_4.setStretch(9, 3)
        self.horizontalLayout_4.setStretch(10, 4)

        self.verticalLayout_2.addLayout(self.horizontalLayout_4)


        self.verticalLayout.addWidget(self.Keyboard)

        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(2, 4)

        self.gridLayout.addWidget(self.Combined, 0, 0, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1046, 22))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Wordle", None))
        self.theme.setText(QCoreApplication.translate("MainWindow", u"Theme", None))
        self.rules.setText(QCoreApplication.translate("MainWindow", u"How to play", None))
        self.r4c5.setText("")
        self.r2c2.setText("")
        self.r5c1.setText("")
        self.r4c2.setText("")
        self.r3c5.setText("")
        self.r5c5.setText("")
        self.r3c1.setText("")
        self.r4c4.setText("")
        self.r2c5.setText("")
        self.r1c2.setText("")
        self.r3c3.setText("")
        self.r6c1.setText("")
        self.r3c4.setText("")
        self.r1c4.setText("")
        self.r2c3.setText("")
        self.r4c1.setText("")
        self.r6c4.setText("")
        self.r2c4.setText("")
        self.r6c3.setText("")
        self.r6c2.setText("")
        self.r5c3.setText("")
        self.r5c2.setText("")
        self.r3c2.setText("")
        self.r2c1.setText("")
        self.r1c3.setText("")
        self.r1c5.setText("")
        self.r1c1.setText("")
        self.r6c5.setText("")
        self.r5c4.setText("")
        self.r4c3.setText("")
        self.qq.setText(QCoreApplication.translate("MainWindow", u"Q", None))
#if QT_CONFIG(shortcut)
        self.qq.setShortcut(QCoreApplication.translate("MainWindow", u"Q", None))
#endif // QT_CONFIG(shortcut)
        self.ww.setText(QCoreApplication.translate("MainWindow", u"W", None))
#if QT_CONFIG(shortcut)
        self.ww.setShortcut(QCoreApplication.translate("MainWindow", u"W", None))
#endif // QT_CONFIG(shortcut)
        self.ee.setText(QCoreApplication.translate("MainWindow", u"E", None))
#if QT_CONFIG(shortcut)
        self.ee.setShortcut(QCoreApplication.translate("MainWindow", u"E", None))
#endif // QT_CONFIG(shortcut)
        self.rr.setText(QCoreApplication.translate("MainWindow", u"R", None))
#if QT_CONFIG(shortcut)
        self.rr.setShortcut(QCoreApplication.translate("MainWindow", u"R", None))
#endif // QT_CONFIG(shortcut)
        self.tt.setText(QCoreApplication.translate("MainWindow", u"T", None))
#if QT_CONFIG(shortcut)
        self.tt.setShortcut(QCoreApplication.translate("MainWindow", u"T", None))
#endif // QT_CONFIG(shortcut)
        self.yy.setText(QCoreApplication.translate("MainWindow", u"Y", None))
#if QT_CONFIG(shortcut)
        self.yy.setShortcut(QCoreApplication.translate("MainWindow", u"Y", None))
#endif // QT_CONFIG(shortcut)
        self.uu.setText(QCoreApplication.translate("MainWindow", u"U", None))
#if QT_CONFIG(shortcut)
        self.uu.setShortcut(QCoreApplication.translate("MainWindow", u"U", None))
#endif // QT_CONFIG(shortcut)
        self.ii.setText(QCoreApplication.translate("MainWindow", u"I", None))
#if QT_CONFIG(shortcut)
        self.ii.setShortcut(QCoreApplication.translate("MainWindow", u"I", None))
#endif // QT_CONFIG(shortcut)
        self.oo.setText(QCoreApplication.translate("MainWindow", u"O", None))
#if QT_CONFIG(shortcut)
        self.oo.setShortcut(QCoreApplication.translate("MainWindow", u"O", None))
#endif // QT_CONFIG(shortcut)
        self.pp.setText(QCoreApplication.translate("MainWindow", u"P", None))
#if QT_CONFIG(shortcut)
        self.pp.setShortcut(QCoreApplication.translate("MainWindow", u"P", None))
#endif // QT_CONFIG(shortcut)
        self.aa.setText(QCoreApplication.translate("MainWindow", u"A", None))
#if QT_CONFIG(shortcut)
        self.aa.setShortcut(QCoreApplication.translate("MainWindow", u"A", None))
#endif // QT_CONFIG(shortcut)
        self.ss.setText(QCoreApplication.translate("MainWindow", u"S", None))
#if QT_CONFIG(shortcut)
        self.ss.setShortcut(QCoreApplication.translate("MainWindow", u"S", None))
#endif // QT_CONFIG(shortcut)
        self.dd.setText(QCoreApplication.translate("MainWindow", u"D", None))
#if QT_CONFIG(shortcut)
        self.dd.setShortcut(QCoreApplication.translate("MainWindow", u"D", None))
#endif // QT_CONFIG(shortcut)
        self.ff.setText(QCoreApplication.translate("MainWindow", u"F", None))
#if QT_CONFIG(shortcut)
        self.ff.setShortcut(QCoreApplication.translate("MainWindow", u"F", None))
#endif // QT_CONFIG(shortcut)
        self.gg.setText(QCoreApplication.translate("MainWindow", u"G", None))
#if QT_CONFIG(shortcut)
        self.gg.setShortcut(QCoreApplication.translate("MainWindow", u"G", None))
#endif // QT_CONFIG(shortcut)
        self.hh.setText(QCoreApplication.translate("MainWindow", u"H", None))
#if QT_CONFIG(shortcut)
        self.hh.setShortcut(QCoreApplication.translate("MainWindow", u"H", None))
#endif // QT_CONFIG(shortcut)
        self.jj.setText(QCoreApplication.translate("MainWindow", u"J", None))
#if QT_CONFIG(shortcut)
        self.jj.setShortcut(QCoreApplication.translate("MainWindow", u"J", None))
#endif // QT_CONFIG(shortcut)
        self.kk.setText(QCoreApplication.translate("MainWindow", u"K", None))
#if QT_CONFIG(shortcut)
        self.kk.setShortcut(QCoreApplication.translate("MainWindow", u"K", None))
#endif // QT_CONFIG(shortcut)
        self.ll.setText(QCoreApplication.translate("MainWindow", u"L", None))
#if QT_CONFIG(shortcut)
        self.ll.setShortcut(QCoreApplication.translate("MainWindow", u"L", None))
#endif // QT_CONFIG(shortcut)
        self.enter.setText(QCoreApplication.translate("MainWindow", u"Enter", None))
#if QT_CONFIG(shortcut)
        self.enter.setShortcut(QCoreApplication.translate("MainWindow", u"Return", None))
#endif // QT_CONFIG(shortcut)
        self.zz.setText(QCoreApplication.translate("MainWindow", u"Z", None))
#if QT_CONFIG(shortcut)
        self.zz.setShortcut(QCoreApplication.translate("MainWindow", u"Z", None))
#endif // QT_CONFIG(shortcut)
        self.xx.setText(QCoreApplication.translate("MainWindow", u"X", None))
#if QT_CONFIG(shortcut)
        self.xx.setShortcut(QCoreApplication.translate("MainWindow", u"X", None))
#endif // QT_CONFIG(shortcut)
        self.cc.setText(QCoreApplication.translate("MainWindow", u"C", None))
#if QT_CONFIG(shortcut)
        self.cc.setShortcut(QCoreApplication.translate("MainWindow", u"C", None))
#endif // QT_CONFIG(shortcut)
        self.vv.setText(QCoreApplication.translate("MainWindow", u"V", None))
#if QT_CONFIG(shortcut)
        self.vv.setShortcut(QCoreApplication.translate("MainWindow", u"V", None))
#endif // QT_CONFIG(shortcut)
        self.bb.setText(QCoreApplication.translate("MainWindow", u"B", None))
#if QT_CONFIG(shortcut)
        self.bb.setShortcut(QCoreApplication.translate("MainWindow", u"B", None))
#endif // QT_CONFIG(shortcut)
        self.nn.setText(QCoreApplication.translate("MainWindow", u"N", None))
#if QT_CONFIG(shortcut)
        self.nn.setShortcut(QCoreApplication.translate("MainWindow", u"N", None))
#endif // QT_CONFIG(shortcut)
        self.mm.setText(QCoreApplication.translate("MainWindow", u"M", None))
#if QT_CONFIG(shortcut)
        self.mm.setShortcut(QCoreApplication.translate("MainWindow", u"M", None))
#endif // QT_CONFIG(shortcut)
        self.Backspace.setText(QCoreApplication.translate("MainWindow", u"Backspace", None))
#if QT_CONFIG(shortcut)
        self.Backspace.setShortcut(QCoreApplication.translate("MainWindow", u"Backspace", None))
#endif // QT_CONFIG(shortcut)
    # retranslateUi

